# Generated by Django 3.2.3 on 2021-09-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('cardid', models.TextField(primary_key=True, serialize=False, verbose_name='cardID')),
                ('owner', models.TextField(blank=True, verbose_name='Owner')),
                ('name', models.TextField(blank=True, verbose_name='Name Surname')),
                ('position', models.TextField(blank=True, verbose_name='Position')),
                ('company', models.TextField(blank=True, verbose_name='Company')),
                ('website', models.TextField(blank=True, verbose_name='Web Site')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('gsm', models.TextField(blank=True, verbose_name='GSM')),
                ('fax', models.TextField(blank=True, verbose_name='Fax')),
                ('instagramacc', models.TextField(blank=True, verbose_name='Instagram Account')),
                ('twitteracc', models.TextField(blank=True, verbose_name='Twitter Account')),
                ('linkedinacc', models.TextField(blank=True, verbose_name='LinkedIn Account Link')),
            ],
        ),
    ]
