# Generated by Django 3.2.3 on 2021-09-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='cardcode',
            field=models.TextField(default=123456789, verbose_name='cardCODE'),
            preserve_default=False,
        ),
    ]
