# Generated by Django 3.2.3 on 2021-09-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_cards_cardcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
    ]
